### ISSUE TITLE
Utilize Bootstrap panel for recipe gallery

### ISSUE THREAD

**Issue by pscholtes** [acadotnet/Pinch#7]
Using [panels ](http://getbootstrap.com/docs/3.3/components/#panels) we want to display high-information about each Recipe in the gallery view (e.g picture, name, description). 

With panels, we will want to list items in `<div class="row">` and `<div class="col">` not repeating items in a `<tr>` and `<tbody>`. So we need to update our code to determine how to generate markup with 4 recipes per row, determining when to open/close a `col` or `row` element

**Comment by reach2gauri** [comment]
I have applied the logic but the web page seems to display Razorview code as well.  Could you please have a look at this one.

**Comment by pscholtes** [comment]
Hey @reach2gauri just add a `@` symbol infront of your `C#` code to tell VS that you're writing code, not markup. 

https://github.com/acadotnet/Pinch/blob/2e9f4c836c34d30d06235459ca6134ce07ce1feb/Pinch/Views/Home/Gallery.cshtml#L13

That can be `@while`

**Comment by reach2gauri** [comment]
I tried that. But then it does not consider COL-SM-4 and which means all the images are being displayed in new row. This is what happening right now. Not sure why! Do you think my logic is faulty??
